# Generated by Django 4.1 on 2022-10-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
