# Generated by Django 4.1.7 on 2023-08-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='previous_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
