# Generated by Django 4.1 on 2022-10-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_product_image_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coverageLength',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
