# Generated by Django 4.1 on 2022-10-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_discount_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='ord',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
