# Generated by Django 4.1 on 2022-11-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_picture_ord'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='physicPerson',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='first_name',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
