const ADMIN = {
  CREATE_PRODUCT_REQUEST: "CREATE_PRODUCT_REQUEST",
  CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",
  CREATE_PRODUCT_FAIL: "CREATE_PRODUCT_FAIL",

  UPDATE_PRODUCT_REQUEST: "UPDATE_PRODUCT_REQUEST",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_FAIL: "UPDATE_PRODUCT_FAIL",

  UPDATE_PRODUCT_RESET: "UPDATE_PRODUCT_RESET",

  DELETE_PRODUCT_REQUEST: "DELETE_PRODUCT_REQUEST",
  DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_FAIL: "DELETE_PRODUCT_FAIL",

  GET_USERS_REQUEST: "GET_USERS_REQUEST",
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  GET_USERS_FAIL: "GET_USERS_FAIL",

  DELETE_USER_REQUEST: "DELETE_USER_REQUEST",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAIL: "DELETE_USER_FAIL",

  GET_USER_REQUEST: "GET_USER_REQUEST",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FAIL: "GET_USER_FAIL",

  UPDATE_USER_REQUEST: "UPDATE_USER_REQUEST",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAIL: "UPDATE_USER_FAIL",

  GET_VARIANTS_REQUEST: "GET_VARIANTS_REQUEST",
  GET_VARIANTS_SUCCESS: "GET_VARIANTS_SUCCESS",
  GET_VARIANTS_FAIL: "GET_VARIANTS_FAIL",

  UPDATE_VARIANT_REQUEST: "UPDATE_VARIANT_REQUEST",
  UPDATE_VARIANT_SUCCESS: "UPDATE_VARIANT_SUCCESS",
  UPDATE_VARIANT_FAIL: "UPDATE_VARIANT_FAIL",

  DELETE_VARIANT_REQUEST: "DELETE_VARIANT_REQUEST",
  DELETE_VARIANT_SUCCESS: "DELETE_VARIANT_SUCCESS",
  DELETE_VARIANT_FAIL: "DELETE_VARIANT_FAIL",

  CREATE_VARIANT_REQUEST: "CREATE_VARIANT_REQUEST",
  CREATE_VARIANT_SUCCESS: "CREATE_VARIANT_SUCCESS",
  CREATE_VARIANT_FAIL: "CREATE_VARIANT_FAIL",

  GET_COLORS_REQUEST: "GET_COLORS_REQUEST",
  GET_COLORS_SUCCESS: "GET_COLORS_SUCCESS",
  GET_COLORS_FAIL: "GET_COLORS_FAIL",
};

export default ADMIN;
