const ADMIN = {
  CREATE_PRODUCT_REQUEST: "CREATE_PRODUCT_REQUEST",
  CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",
  CREATE_PRODUCT_FAIL: "CREATE_PRODUCT_FAIL",

  UPDATE_PRODUCT_REQUEST: "UPDATE_PRODUCT_REQUEST",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_FAIL: "UPDATE_PRODUCT_FAIL",

  UPDATE_PRODUCT_RESET: "UPDATE_PRODUCT_RESET",

  DELETE_PRODUCT_REQUEST: "DELETE_PRODUCT_REQUEST",
  DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_FAIL: "DELETE_PRODUCT_FAIL",

  GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  GET_PRODUCT_FAIL: "GET_PRODUCT_FAIL",

  GET_USERS_REQUEST: "GET_USERS_REQUEST",
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  GET_USERS_FAIL: "GET_USERS_FAIL",

  DELETE_USER_REQUEST: "DELETE_USER_REQUEST",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAIL: "DELETE_USER_FAIL",

  GET_USER_REQUEST: "GET_USER_REQUEST",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FAIL: "GET_USER_FAIL",

  UPDATE_USER_REQUEST: "UPDATE_USER_REQUEST",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAIL: "UPDATE_USER_FAIL",

  GET_VARIANTS_REQUEST: "GET_VARIANTS_REQUEST",
  GET_VARIANTS_SUCCESS: "GET_VARIANTS_SUCCESS",
  GET_VARIANTS_FAIL: "GET_VARIANTS_FAIL",

  UPDATE_VARIANT_REQUEST: "UPDATE_VARIANT_REQUEST",
  UPDATE_VARIANT_SUCCESS: "UPDATE_VARIANT_SUCCESS",
  UPDATE_VARIANT_FAIL: "UPDATE_VARIANT_FAIL",

  DELETE_VARIANT_REQUEST: "DELETE_VARIANT_REQUEST",
  DELETE_VARIANT_SUCCESS: "DELETE_VARIANT_SUCCESS",
  DELETE_VARIANT_FAIL: "DELETE_VARIANT_FAIL",

  CREATE_VARIANT_REQUEST: "CREATE_VARIANT_REQUEST",
  CREATE_VARIANT_SUCCESS: "CREATE_VARIANT_SUCCESS",
  CREATE_VARIANT_FAIL: "CREATE_VARIANT_FAIL",

  GET_COLORS_REQUEST: "GET_COLORS_REQUEST",
  GET_COLORS_SUCCESS: "GET_COLORS_SUCCESS",
  GET_COLORS_FAIL: "GET_COLORS_FAIL",

  CREATE_CATEGORY_REQUEST: "CREATE_CATEGORY_REQUEST",
  CREATE_CATEGORY_SUCCESS: "CREATE_CATEGORY_SUCCESS",
  CREATE_CATEGORY_FAIL: "CREATE_CATEGORY_FAIL",

  DELETE_CATEGORY_REQUEST: "DELETE_CATEGORY_REQUEST",
  DELETE_CATEGORY_SUCCESS: "DELETE_CATEGORY_SUCCESS",
  DELETE_CATEGORY_FAIL: "DELETE_CATEGORY_FAIL",

  DELETE_IMAGE_REQUEST: "DELETE_IMAGE_REQUEST",
  DELETE_IMAGE_SUCCESS: "DELETE_IMAGE_SUCCESS",
  DELETE_IMAGE_FAIL: "DELETE_IMAGE_FAIL",

  CREATE_IMAGE_REQUEST: "CREATE_IMAGE_REQUEST",
  CREATE_IMAGE_SUCCESS: "CREATE_IMAGE_SUCCESS",
  CREATE_IMAGE_FAIL: "CREATE_IMAGE_FAIL",

  GET_IMAGES_REQUEST: "GET_IMAGES_REQUEST",
  GET_IMAGES_SUCCESS: "GET_IMAGES_SUCCESS",
  GET_IMAGES_FAIL: "GET_IMAGES_FAIL",

  GET_ORDER_LIST_REQUEST: "GET_ORDER_LIST_REQUEST",
  GET_ORDER_LIST_SUCCESS: "GET_ORDER_LIST_SUCCESS",
  GET_ORDER_LIST_FAIL: "GET_ORDER_LIST_FAIL",

  DELETE_ORDER_REQUEST: "DELETE_ORDER_REQUEST",
  DELETE_ORDER_SUCCESS: "DELETE_ORDER_SUCCESS",
  DELETE_ORDER_FAIL: "DELETE_ORDER_FAIL",

  ORDER_DELIVERED_REQUEST: "ORDER_DELIVERED_REQUEST",
  ORDER_DELIVERED_SUCCESS: "ORDER_DELIVERED_SUCCESS",
  ORDER_DELIVERED_FAIL: "ORDER_DELIVERED_FAIL",
};

export default ADMIN;
