const DISCOUNT = {
  GET_DISCOUNT_REQUEST: "GET_DISCOUNT_REQUEST",
  GET_DISCOUNT_SUCCESS: "GET_DISCOUNT_SUCCESS",
  GET_DISCOUNT_FAIL: "GET_DISCOUNT_FAIL",

  CREATE_DISCOUNT_REQUEST: "CREATE_DISCOUNT_REQUEST",
  CREATE_DISCOUNT_SUCCESS: "CREATE_DISCOUNT_SUCCESS",
  CREATE_DISCOUNT_FAIL: "CREATE_DISCOUNT_FAIL",

  DELETE_DISCOUNT_REQUEST: "CREATE_DELETE_REQUEST",
  DELETE_DISCOUNT_SUCCESS: "CREATE_DELETE_SUCCESS",
  DELETE_DISCOUNT_FAIL: "CREATE_DELETE_FAIL",
};

export default DISCOUNT;
