const DISCOUNT = {
  GET_DISCOUNT_REQUEST: "GET_DISCOUNT_REQUEST",
  GET_DISCOUNT_SUCCESS: "GET_DISCOUNT_SUCCESS",
  GET_DISCOUNT_FAIL: "GET_DISCOUNT_FAIL",

  CREATE_DISCOUNT_REQUEST: "CREATE_DISCOUNT_REQUEST",
  CREATE_DISCOUNT_SUCCESS: "CREATE_DISCOUNT_SUCCESS",
  CREATE_DISCOUNT_FAIL: "CREATE_DISCOUNT_FAIL",

  UPDATE_DISCOUNT_REQUEST: "UPDATE_DISCOUNT_REQUEST",
  UPDATE_DISCOUNT_SUCCESS: "UPDATE_DISCOUNT_SUCCESS",
  UPDATE_DISCOUNT_FAIL: "UPDATE_DISCOUNT_FAIL",

  DELETE_DISCOUNT_REQUEST: "DELETE_DISCOUNT_REQUEST",
  DELETE_DISCOUNT_SUCCESS: "DELETE_DISCOUNT_SUCCESS",
  DELETE_DISCOUNT_FAIL: "DELETE_DISCOUNT_FAIL",

  GET_PRODUCTS_REQUEST: "GET_PRODUCTS_REQUEST",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAIL: "GET_PRODUCTS_FAIL",

  GET_USERS_REQUEST: "GET_USERS_REQUEST",
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  GET_USERS_FAIL: "GET_USERS_FAIL",
};

export default DISCOUNT;
