const ORDER = {
  CREATE_REQUEST: "CREATE_REQUEST",
  CREATE_SUCCESS: "CREATE_SUCCESS",
  CREATE_FAIL: "CREATE_FAIL",

  DELIVERED_REQUEST: "DELIVERED_REQUEST",
  DELIVERED_SUCCESS: "DELIVERED_SUCCESS",
  DELIVERED_FAIL: "DELIVERED_FAIL",
}


export default ORDER