const SHIPPING = {
  GET_PRICES_REQUEST: "GET_PRICES_REQUEST",
  GET_PRICES_SUCCESS: "GET_PRICES_SUCCESS",
  GET_PRICES_FAIL: "GET_PRICES_FAIL",

  GET_SHIPPING_REQUEST: "GET_SHIPPING_REQUEST",
  SAVE_SHIPPING_PAYMENT_METHOD: "GET_SHIPPING_PAYMENT_METHOD",
  SAVE_SHIPPING_DETAILS: "SAVE_SHIPPING_DETAILS",
  SAVE_SHIPPING_METHOD: "SAVE_SHIPPING_METHOD",
  CLEAR_SHIPPING_ITEMS: "CLEAR_SHIPPING_ITEMS",
};

export default SHIPPING;
