const SHIPPING = {
  GET_PRICES_REQUEST: "GET_PRICES_REQUEST",
  GET_PRICES_SUCCESS: "GET_PRICES_SUCCESS",
  GET_PRICES_FAIL: "GET_PRICES_FAIL",

  CREATE_CITY_REQUEST: "CREATE_CITY_REQUEST",
  CREATE_CITY_SUCCESS: "CREATE_CITY_SUCCESS",
  CREATE_CITY_FAIL: "CREATE_CITY_FAIL",

  UPDATE_CITY_REQUEST: "UPDATE_CITY_REQUEST",
  UPDATE_CITY_SUCCESS: "UPDATE_CITY_SUCCESS",
  UPDATE_CITY_FAIL: "UPDATE_CITY_FAIL",

  DELETE_CITY_REQUEST: "DELETE_CITY_REQUEST",
  DELETE_CITY_SUCCESS: "DELETE_CITY_SUCCESS",
  DELETE_CITY_FAIL: "DELETE_CITY_FAIL",

  GET_SHIPPING_REQUEST: "GET_SHIPPING_REQUEST",
  SAVE_SHIPPING_PAYMENT_METHOD: "GET_SHIPPING_PAYMENT_METHOD",
  SAVE_SHIPPING_DETAILS: "SAVE_SHIPPING_DETAILS",
  SAVE_SHIPPING_METHOD: "SAVE_SHIPPING_METHOD",
  CLEAR_SHIPPING_ITEMS: "CLEAR_SHIPPING_ITEMS",
};

export default SHIPPING;
