export const SYSTEM_LOGIN_REQUEST = "SYSTEM_LOGIN_REQUEST";
export const SYSTEM_LOGIN_SUCCESS = "SYSTEM_LOGIN_SUCCESS";
export const SYSTEM_LOGIN_FAIL = "SYSTEM_LOGIN_FAIL";

export const SYSTEM_LOGOUT = "SYSTEM_LOGOUT";

export const SYSTEM_REGISTER_REQUEST="SYSTEM_REGISTER_REQUEST"
export const SYSTEM_REGISTER_SUCCESS="SYSTEM_REGISTER_SUCCESS"
export const SYSTEM_REGISTER_FAIL="SYSTEM_REGISTER_FAIL"