const SYSTEM = {
  GET_CATEGORIES_REQUEST: "GET_CATEGORIES_REQUEST",
  GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
  GET_CATEGORIES_FAIL: "GET_CATEGORIES_FAIL",

  GET_LATEST_PRODUCTS_REQUEST: "GET_LATEST_PRODUCTS_REQUEST",
  GET_LATEST_PRODUCTS_SUCCESS: "GET_LATEST_PRODUCTS_SUCCESS",
  GET_LATEST_PRODUCTS_FAIL: "GET_LATEST_PRODUCTS_FAIL",

  GET_PRODUCTS_REQUEST: "GET_PRODUCTS_REQUEST",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAIL: "GET_PRODUCTS_FAIL",

  GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  GET_PRODUCT_FAIL: "GET_PRODUCT_FAIL",

  GET_PRODUCT_RESET: "GET_PRODUCT_RESET",

  GET_SIMILAR_PRODUCTS_REQUEST: "GET_SIMILAR_PRODUCTS_REQUEST",
  GET_SIMILAR_PRODUCTS_SUCCESS: "GET_SIMILAR_PRODUCTS_SUCCESS",
  GET_SIMILAR_PRODUCTS_FAIL: "GET_SIMILAR_PRODUCTS_FAIL",

  GET_SHIPPING_REQUEST: "GET_SHIPPING_REQUEST",
  SAVE_SHIPPING_PAYMENT_METHOD: "GET_SHIPPING_PAYMENT_METHOD",
  SAVE_SHIPPING_DETAILS: "SAVE_SHIPPING_DETAILS",
  SAVE_SHIPPING_METHOD: "SAVE_SHIPPING_METHOD",
  CLEAR_SHIPPING_REQUEST: "CLEAR_SHIPPING_REQUEST",
};

export default SYSTEM;
