const USER = {
  GET_PROFILE_REQUEST: "GET_PROFILE_REQUEST",
  GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
  GET_PROFILE_FAIL: "GET_PROFILE_FAIL",

  PROFILE_UPDATE_REQUEST: "PROFILE_UPDATE_REQUEST",
  PROFILE_UPDATE_SUCCESS: "PROFILE_UPDATE_SUCCESS",
  PROFILE_UPDATE_FAIL: "PROFILE_UPDATE_FAIL",

  GET_CART_REQUEST: "GET_CART_REQUEST",
  GET_CART_SUCCESS: "GET_CART_SUCCESS",
  GET_CART_FAIL: "GET_CART_FAIL",

  CART_ADD_REQUEST: "CART_ADD_REQUEST",
  CART_ADD_SUCCESS: "CART_ADD_SUCCESS",
  CART_ADD_FAIL: "CART_ADD_FAIL",

  CART_UPDATE_REQUEST: "CART_UPDATE_REQUEST",
  CART_UPDATE_SUCCESS: "CART_UPDATE_SUCCESS",
  CART_UPDATE_FAIL: "CART_UPDATE_FAIL",

  CART_DELETE_REQUEST: "CART_DELETE_REQUEST",
  CART_DELETE_SUCCESS: "CART_DELETE_SUCCESS",
  CART_DELETE_FAIL: "CART_DELETE_FAIL",
};
export default USER;
