const USER = {
  GET_PROFILE_REQUEST: "GET_PROFILE_REQUEST",
  GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
  GET_PROFILE_FAIL: "GET_PROFILE_FAIL",

  PROFILE_UPDATE_REQUEST: "PROFILE_UPDATE_REQUEST",
  PROFILE_UPDATE_SUCCESS: "PROFILE_UPDATE_SUCCESS",
  PROFILE_UPDATE_FAIL: "PROFILE_UPDATE_FAIL",
};
export default USER;
